# Generated by Django 5.1.7 on 2025-04-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='analisadores',
        ),
        migrations.AddField(
            model_name='analisador',
            name='parametros',
            field=models.ManyToManyField(related_name='analisadores_compatíveis', to='calibracao.parametro'),
        ),
    ]
