# Generated by Django 5.1.7 on 2025-04-12 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0002_remove_parametro_analisadores_analisador_parametros'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroCalibrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laudo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_calibrados', to='calibracao.cabcalibracao')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laudos_calibrados', to='calibracao.parametro')),
            ],
        ),
    ]
