# Generated by Django 5.1.7 on 2025-04-23 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibracao', '0003_parametrocalibrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='certificado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='calibracao.certificadoanalisador'),
            preserve_default=False,
        ),
    ]
