# Generated by Django 5.1.7 on 2025-03-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
