# Generated by Django 5.1.7 on 2025-03-21 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_alter_cliente_complemento'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('corretiva interna', 'Corretiva Interna'), ('corretiva externa', 'Corretiva Externa'), ('preventiva interna', 'Preventiva Interna'), ('preventiva externa', 'Preventiva Externa')], max_length=20)),
                ('motivo', models.TextField()),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('aguardando envio do laudo', 'Aguardando Envio do Laudo'), ('executado - aguardando faturamento', 'Executado - Aguardando Faturamento'), ('aguardando envio do orçamento', 'Aguardando Envio do Orçamento'), ('aguardando aprovação', 'Aguardando Aprovação'), ('aguardando peça para continuar orçamento', 'Aguardando Peça para Continuar Orçamento'), ('aprovado - aguardando execução', 'Aprovado - Aguardando Execução'), ('reprovado', 'Reprovado'), ('finalizado', 'Finalizado')], default='aberta', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
            ],
        ),
    ]
