# Generated by Django 5.1.7 on 2025-05-01 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModeloChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CabPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField()),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('temp_ambiente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('umidade_relativa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('executante', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Aberto', max_length=20)),
                ('consideracoes_finais', models.TextField(blank=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventivas', to='ordens.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVerificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Não se aplica', 'Não se aplica')], max_length=20)),
                ('cab_preventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_verificados', to='preventiva.cabpreventiva')),
                ('item_modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventiva.itemmodelochecklist')),
            ],
        ),
        migrations.AddField(
            model_name='itemmodelochecklist',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='preventiva.modelochecklist'),
        ),
    ]
