# Generated by Django 5.1.7 on 2025-05-01 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventiva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabpreventiva',
            name='modelo_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventivas', to='preventiva.modelochecklist'),
        ),
    ]
