# Generated by Django 5.1.7 on 2025-05-03 04:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens', '0001_initial'),
        ('preventiva', '0002_cabpreventiva_modelo_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaudoCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50)),
                ('data_calibracao', models.DateField()),
                ('tecnico_responsavel', models.CharField(max_length=100)),
                ('certificado', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LaudoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField()),
                ('executante', models.CharField(max_length=100)),
                ('responsavel', models.CharField(max_length=100)),
                ('consideracoes_finais', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('cab_preventiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preventiva.cabpreventiva')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordens.ordemservico')),
            ],
        ),
    ]
